import React, { useState, useEffect } from 'react';
import { 
  ShieldCheck, 
  AlertTriangle, 
  Lock, 
  CheckCircle2, 
  X, 
  ArrowRight, 
  HelpCircle,
  CreditCard,
  DollarSign,
  Users,
  Clock,
  Sparkles,
  Sliders,
  Check
} from 'lucide-react';
import { CommerceAction, ActionPolicy } from '../../types/commerce';
import { GrowthOpportunityFull } from '../../types/growth';

interface ActionApprovalModalProps {
  isOpen: boolean;
  onClose: () => void;
  opportunity: GrowthOpportunityFull;
  actionProposal?: CommerceAction | null;
  onApproveAndExecute: (params: {
    approvedAmount: number;
    approvedTargetCount: number;
    approvedBy: string;
    simulateFailure: boolean;
    notes?: string;
  }) => void;
  onReject: (reason: string) => void;
  isExecuting: boolean;
}

export const ActionApprovalModal: React.FC<ActionApprovalModalProps> = ({
  isOpen,
  onClose,
  opportunity,
  actionProposal,
  onApproveAndExecute,
  onReject,
  isExecuting,
}) => {
  const maxCeiling = opportunity.potentialImpactValue || 5000;
  const [approvedAmount, setApprovedAmount] = useState<number>(maxCeiling);
  const [approvedBy, setApprovedBy] = useState<string>('Merchant (jaanvishelar3@gmail.com)');
  const [merchantNotes, setMerchantNotes] = useState<string>('Approved for Razorpay Test Mode recovery campaign.');
  const [simulateFailure, setSimulateFailure] = useState<boolean>(false);
  const [rejectReason, setRejectReason] = useState<string>('');
  const [showRejectForm, setShowRejectForm] = useState<boolean>(false);

  useEffect(() => {
    if (isOpen) {
      setApprovedAmount(opportunity.potentialImpactValue || 5000);
      setSimulateFailure(false);
      setShowRejectForm(false);
    }
  }, [isOpen, opportunity.id, opportunity.potentialImpactValue]);

  if (!isOpen) return null;

  const handleAmountChange = (val: number) => {
    // Strict safety cap: Cannot exceed calculated ceiling
    const clamped = Math.min(Math.max(val, 100), maxCeiling);
    setApprovedAmount(clamped);
  };

  const handleApprove = () => {
    onApproveAndExecute({
      approvedAmount,
      approvedTargetCount: opportunity.targetCount,
      approvedBy: approvedBy.trim() || 'Merchant Admin',
      simulateFailure,
      notes: merchantNotes,
    });
  };

  const handleRejectSubmit = () => {
    onReject(rejectReason || 'Declined by merchant during proposal review.');
    setShowRejectForm(false);
  };

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs z-50 flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-2xl w-full border border-slate-200 shadow-2xl overflow-hidden my-8">
        {/* Top Razorpay Test Mode Banner */}
        <div className="bg-amber-500 text-slate-950 px-4 py-2 text-xs font-bold flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-slate-950 animate-pulse"></span>
            <span>RAZORPAY TEST MODE — ZERO REAL MONEY INVOLVED</span>
          </div>
          <span className="uppercase text-[10px] tracking-wider bg-slate-950 text-amber-300 px-2 py-0.5 rounded font-mono">
            Sandbox Environment
          </span>
        </div>

        {/* Modal Header */}
        <div className="p-6 border-b border-slate-100 flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold text-indigo-600 mb-1 uppercase tracking-wider">
              <ShieldCheck className="w-4 h-4" />
              <span>Human Approval Gate • Bounded Commerce Proposal</span>
            </div>
            <h2 className="text-xl font-bold text-slate-900">{opportunity.title}</h2>
            <p className="text-xs text-slate-500 mt-1">
              Review and sign off on the bounded Razorpay Test action generated by MerchantMind AI.
            </p>
          </div>
          <button
            onClick={onClose}
            disabled={isExecuting}
            className="p-1.5 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-6 max-h-[calc(80vh-12rem)] overflow-y-auto">
          {/* Opportunity Grounded Summary */}
          <div className="bg-slate-50 rounded-xl p-4 border border-slate-200 space-y-3">
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-slate-700">Target Cohort</span>
              <span className="font-bold text-slate-900 bg-white px-2 py-0.5 rounded border border-slate-200">
                {opportunity.targetCount} transactions ({opportunity.targetAudience})
              </span>
            </div>
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-slate-700">Calculated Historical Value</span>
              <span className="font-mono text-slate-900 font-bold">
                {opportunity.historicalValueFormatted || `₹${(opportunity.historicalValueRaw || 0).toLocaleString()}`}
              </span>
            </div>
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-slate-700">AI Bounded Opportunity Bound</span>
              <span className="font-mono text-indigo-600 font-bold text-sm">
                ₹{maxCeiling.toLocaleString()}
              </span>
            </div>
            <div className="text-xs text-slate-600 bg-white p-2.5 rounded-lg border border-slate-200 leading-relaxed">
              <strong className="text-slate-800">Evidence:</strong> {opportunity.evidence}
            </div>
          </div>

          {/* Bounded Financial Slider */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                <DollarSign className="w-3.5 h-3.5 text-emerald-600" />
                <span>Authorized Execution Ceiling</span>
              </label>
              <div className="flex items-center gap-1">
                <span className="text-xs text-slate-400">Hard Cap:</span>
                <span className="text-xs font-mono font-bold text-slate-900">₹{maxCeiling.toLocaleString()}</span>
              </div>
            </div>
            
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-600 font-medium">Merchant Approved Limit:</span>
                <span className="text-lg font-bold font-mono text-emerald-700 bg-emerald-50 px-3 py-1 rounded-lg border border-emerald-200">
                  ₹{approvedAmount.toLocaleString()}
                </span>
              </div>
              <input
                type="range"
                min={100}
                max={maxCeiling}
                step={50}
                value={approvedAmount}
                onChange={(e) => handleAmountChange(Number(e.target.value))}
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
              />
              <div className="flex justify-between text-[10px] text-slate-400 font-mono">
                <span>₹100 (Min)</span>
                <span>Max Allowed: ₹{maxCeiling.toLocaleString()}</span>
              </div>
            </div>
          </div>

          {/* 12 Bounded Safety Policies Checklist */}
          <div className="space-y-2">
            <div className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
              <Lock className="w-3.5 h-3.5 text-indigo-600" />
              <span>12 Enforced Safety & Governance Guardrails</span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] text-slate-700">
              <div className="flex items-center gap-2 p-2 bg-emerald-50/60 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Zero Auto-Execute (Human Gated)</span>
              </div>
              <div className="flex items-center gap-2 p-2 bg-emerald-50/60 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Live Mode Blocked (Test Mode Only)</span>
              </div>
              <div className="flex items-center gap-2 p-2 bg-emerald-50/60 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Amount Ceiling Strictly Enforced</span>
              </div>
              <div className="flex items-center gap-2 p-2 bg-emerald-50/60 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Idempotency Key Prevents Duplication</span>
              </div>
              <div className="flex items-center gap-2 p-2 bg-emerald-50/60 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Immutable Audit Logging</span>
              </div>
              <div className="flex items-center gap-2 p-2 bg-emerald-50/60 rounded-lg border border-emerald-100">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>Secrets Never Stored in Logs/Client</span>
              </div>
            </div>
          </div>

          {/* Merchant Sign-off Identifier */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-800">
              Approving Merchant Authority
            </label>
            <input
              type="text"
              value={approvedBy}
              onChange={(e) => setApprovedBy(e.target.value)}
              placeholder="e.g. Merchant (jaanvishelar3@gmail.com)"
              className="w-full px-3 py-2 text-xs bg-white border border-slate-200 rounded-lg font-medium text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          {/* Controlled Failure Demo Checkbox (For Judges) */}
          <div className="p-3 bg-amber-50 rounded-xl border border-amber-200">
            <label className="flex items-start gap-2.5 cursor-pointer">
              <input
                type="checkbox"
                checked={simulateFailure}
                onChange={(e) => setSimulateFailure(e.target.checked)}
                className="mt-0.5 h-4 w-4 rounded border-amber-300 text-amber-600 focus:ring-amber-500"
              />
              <div>
                <span className="text-xs font-bold text-amber-900">
                  Simulate Controlled Test Failure (Judges Demo Mode)
                </span>
                <p className="text-[11px] text-amber-800 mt-0.5 leading-relaxed">
                  Triggers a simulated Razorpay gateway timeout. Proves that the system records the failure in the audit trail, protects state, and enables safe idempotent retry.
                </p>
              </div>
            </label>
          </div>

          {/* Rejection Sub-form */}
          {showRejectForm && (
            <div className="p-4 bg-rose-50 rounded-xl border border-rose-200 space-y-2">
              <span className="text-xs font-bold text-rose-900">Specify Rejection Reason:</span>
              <textarea
                value={rejectReason}
                onChange={(e) => setRejectReason(e.target.value)}
                placeholder="e.g., Campaign timing not optimal, budget paused."
                className="w-full text-xs p-2.5 bg-white border border-rose-200 rounded-lg text-slate-800"
                rows={2}
              />
              <div className="flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setShowRejectForm(false)}
                  className="px-3 py-1 text-xs text-slate-600 hover:text-slate-800"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleRejectSubmit}
                  className="px-3 py-1 text-xs bg-rose-600 text-white font-bold rounded-lg hover:bg-rose-700"
                >
                  Confirm Rejection
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 bg-slate-50 border-t border-slate-100 flex items-center justify-between gap-3">
          {!showRejectForm ? (
            <button
              type="button"
              onClick={() => setShowRejectForm(true)}
              disabled={isExecuting}
              className="px-4 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50 rounded-lg transition-colors border border-transparent hover:border-rose-200"
            >
              Decline Proposal
            </button>
          ) : (
            <div></div>
          )}

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClose}
              disabled={isExecuting}
              className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-200 rounded-lg transition-colors"
            >
              Cancel
            </button>

            <button
              type="button"
              onClick={handleApprove}
              disabled={isExecuting}
              className="px-5 py-2 text-xs font-bold bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-sm flex items-center gap-2 disabled:opacity-50"
            >
              {isExecuting ? (
                <>
                  <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                  <span>Executing in Test Mode...</span>
                </>
              ) : (
                <>
                  <Check className="w-3.5 h-3.5" />
                  <span>Approve & Execute Test Action</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
